# Generated by Django 5.1.6 on 2025-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0004_alter_complaintupdate_complaint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentofficial",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentofficial",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
